### PR TITLE
All pure neuron serial simulation specification and control functions and classes available via matlab without python

### LINKED ISSUE #4: All pure-NEURON serial simulation specification and control functions and classes available via MATLAB without Python
For the sake of this issue, we can exclude things that depend on Python like NeuroML export or reaction-diffusion model specification.

This aim definitely includes:

Global values:

- [ ] t
- [ ] dt
- [ ] celsius
- [ ] secondorder (a flag which partly specifies integration method)

Functions:
- [ ] fadvance
- [ ] finitialize
- [ ] allsec
- [ ] continuerun
- [ ] topology (although if this could be output in a way that could be programmatically processed in addition to being displayed, that would be better)

Built-in point processes:
- [ ] IClamp
- [ ] SEClamp
- [ ] VClamp
- [ ] IClamp
- [ ] ExpSyn
- [ ] Exp2Syn
- [ ] AlphaSynapse

Artificial cells:

- [ ] PatternStim
- [ ] IntFire1
- [ ] IntFire2
- [ ] IntFire4

Classes:
- [ ] Section (in particular, this includes: getting/setting properties, getting segments, connecting to a section or segment, inserting density mechanisms, getting wholetree -- the list of all connected Sections, pt3d manipulation, psection)
- [ ] Segment (in particular including a way to access values and pointers for e.g. `seg.hh.m`, `seg.nai`, `seg.ina`; finding the section and normalized position)
- [ ] Pointer or alternative (should encapsulate information about section so e.g. don't need to pass that to a NetCon)
- [ ] NetStim
- [ ] NetCon (all networks that are built ought to be done in a way that will just work with parallel)
- [ ] Vector (in particular: recording and playing, converting to_matlab like to_python, initializing from MATLAB array)
- [ ] CVode 
- [ ] SaveState
- [ ] Random (and especially the `Random.Random123` mechanism which is essential for reproducible randomness in parallel simulations)
- [ ] LinearMechanism

Really, FInitializeHandler should be on this list, but it's so important it's #11 .

See [nrn.readthedocs.io](https://nrn.readthedocs.io) for information on these items.

### LINKED ISSUE #62: Implement v(end) for vector indexing
We can currently access vector elements directly:

```matlab
v = n.Vector([1, 2, 3]);
disp(v(1));  % Displays: 1
```

However, we cannot access the last element with:

```matlab
disp(v(end));  % Displays first element: 1
```

There should be a quick fix, see https://nl.mathworks.com/matlabcentral/answers/502794-how-to-detect-the-end-directive-in-subsref

### LINKED ISSUE #66: Methods returning new objects
How do we deal with methods that return new objects? For example `Vector.c()` and (probably) `ParallelContext.gid_connect(i, cell)`.

### LINKED ISSUE #68: Deleting NEURON Objects
The user currently has to explicitly delete any NEURON Objects by running `Object.delete_nrn_obj()` in MATLAB. If this method were named `Object.delete()` it would lead to unexpected behaviour, such as deleting a vector upon calling `Vector.append()` without catching the output.

Instead we could keep track of whether the MATLAB Object is the owner of the NEURON Object, and if so, run `Object.delete_nrn_obj()` upon `Object.delete()`.

### PR DESCRIPTION
**Pull request by edovanveen**
Closes #4 , closes #62, closes #66, closes #68, partial fix for #61 (allsec)

### CODE REVIEW

**Comment by edovanveen** [comment]
This PR was inadvertently closed by the intermediate issue #4 pull request, after which I rebased branch 4-all-pure-... on main, but there were no differences.

File: +neuron/Vector.m [hunk 1]
```diff
@@ -71,6 +71,23 @@
         %   value = length()
             value = self.call_method_hoc('size', 'double');
         end
+        
+        function value = size(self)
+        % Get Vector size.
+        %   value = size()
+            value = [1 self.length()];
```
Comment (ramcdougal) [inline +neuron/Vector.m:78]: Do we have a document somewhere of where things behave differently between MATLAB and the other languages? If so, we should create one and this should be on it.

Because in Python and HOC, there's also a `Vector.size()` but there it returns a scalar. 

https://nrn.readthedocs.io/en/8.2.2/python/programming/math/vector.html#Vector.size

File: +neuron/Object.m [hunk 2]
```diff
@@ -141,12 +141,6 @@ function list_methods(self)
             % Are we trying to directly access a class property?
             elseif (isa(method, "char") && length(S) == 1 && isprop(self, method))
                 [varargout{1:nargout}] = self.(method);
-            % Special case: size
-            % If we make an array of Objects, and ask for its size, Matlab
-            % throws an error if we don't exclude this special case here.
-            % TODO: check behavior for Objects other than Vector.
-            elseif (method == "size")
-                % Do nothing; method is replaced by self.length().
```
Comment (ramcdougal) [inline +neuron/Object.m:149]: Besides `Vector`, there is also a `.size` method for: `PlotShape`, `Shape`, `PtrVector`, `VBox`, `HBox`, and `Graph`.

File: examples/example_temptest.m [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+n.celsius = 37;
+n.finitialize(-65);
+n.continuerun(10);
+
+disp(length(t_spikes));  % 0
+
+
+% Revert back to non-variable step for next run.
+cv.active(0);
+n.dt = 0.025;
```
Comment (ramcdougal) [inline examples/example_temptest.m:59]: This example starts out by setting Celsius to 6.3, which is the default, but the others don't, so if you run anything else after this you may get unexpected numbers... Maybe we should set the temperature back to 6.3 as part of the cleanup here too?

File: examples/example_temptest.m [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+
+nc_recorder = n.NetCon(soma(0.5).ref("v"), n.null);
+t_spikes = n.Vector();
+nc_recorder.record(t_spikes);
+
+n.finitialize(-65);
+n.continuerun(10);
+
+disp(length(t_spikes));  % 1
+disp(t_spikes(1));  % 6.1000 (on first run only)
```
Comment (ramcdougal) [inline examples/example_temptest.m:38]: Is the first run only comment still true, or did resetting code to fixed step fix that?

File: +neuron/Section.m [hunk 5]
```diff
@@ -169,6 +169,10 @@ function insert_mechanism(self, mech_name)
                 end
             end
         end
+        function insert(self, mech_name)
```
Comment (ramcdougal) [inline +neuron/Section.m:172]: Thanks for promoting consistency across the platforms.

File: examples/example_temptest.m (hunk 4 above)
Comment (edovanveen) [reply examples/example_temptest.m:38]: Resetting fixes that.

I also tried fixing it by making a `SavedState` at the first initialization of Neuron, which is then restored every time `n = neuron.Neuron()` is run, but that did not work.

**Comment by edovanveen** [comment]
Remaining problems:
- How to get/set point properties that are arrays?
- Why does changing `n.secondorder` not have any effect? Might be related to other issues in that example, so let's fix those first.
- How to deal with methods that return new objects, such as `vec.c()` and (probably) `pc.gid_connect(i, cell)`? (_Move to new issue._)
- Should we completely reset the Neuron state every time we rerun a script? (_If yes, move to new issue._)

**Comment by ramcdougal** [comment]
Arrays are contiguous and their start position index can be found with `hoc_table_lookup`; e.g. if you do

```C++
double* pp_property_ptr(Object* pp, const char* name) {
    int index = hoc_table_lookup(name, pp->ctemplate->symtable)->u.rng.index;
    return ob2pntproc_0(pp)->prop->param + index;
}
```

Then the following:
```C++
nrn_pushsec(axon);
hoc_pushx(0.5);
auto vclamp = hoc_newobj1(hoc_lookup("VClamp"), 1);
nrn_sec_pop();

auto vclamp_amp = pp_property_ptr(vclamp, "amp");
vclamp_amp[0] = 0;
vclamp_amp[1] = 10;
vclamp_amp[2] = 5;
```

is equivalent to Python's
```python
vclamp = h.VClamp(axon(0.5))
vclamp.amp[0] = 0
vclamp.amp[1] = 10
vclamp.amp[2] = 5
```

See https://github.com/mcdougallab/neuron-c-api-demos/blob/main/vclamp/vclamp.cpp which uses a 2-electrode voltage clamp to (attempt to) clamp the cell to 0 mV for 1 ms, then to 10 mV for the next 2 ms, and finally to 5 mV for the next 3 ms.

**Comment by edovanveen** [comment]
All remaining problems are fixed. I will set this PR to 'ready' after I go through the changes and update the documentation/comments.

**Comment by edovanveen** [comment]
Note: example scripts will be organized and asserts will be added in PR #63

File: +neuron/Vector.m (hunk 1 above)
Comment (edovanveen) [reply +neuron/Vector.m:82]: Added section to readme.

**Comment by edovanveen** [comment]
@ramcdougal ready for review

File: +neuron/Object.m [hunk 6]
```diff
@@ -72,11 +72,10 @@ function delete(self)
         % Decrease refcount by 1; if refcount is 0, release the C++ Object.
         %   delete()
 
-            self.obj.refcount = self.obj.refcount - 1;
+            clib.neuron.hoc_obj_unref(self.obj);
 
             % We need to do this, or else we get crashes.
             if self.obj.refcount == 0
```
Comment (ramcdougal) [inline +neuron/Object.m:78]: You've tested to make sure that this works? I'd worry that if refcount goes to 0 and NEURON releases the memory, that we wouldn't be able to check self.obj.refcount... unless the need for `clibRelease` is somehow keeping us safe?

Comment (edovanveen) [reply +neuron/Object.m]: Yes, I tested it - checking `refcount` worked.

With this version it even works without `clibRelease`, so checking `refcount` is not even necessary. So that issue has been solved then. The `n.List()` counts are 0, and the tests run without issue.
